version: '3.8'

services:
  fantacalcio-postgres:
    image: postgres:15
    container_name: fantacalcio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fantacalcio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fantacalcio-net

  eureka-server:
    build:
      context: ./backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - fantacalcio-net

  user-service:
    build:
      context: ./backend/user-service
    container_name: user-service
    depends_on:
      - fantacalcio-postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fantacalcio-postgres:5432/fantacalcio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: your-secret-key
      JWT_EXPIRATION: 86400000
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - fantacalcio-net

  api-gateway:
    build:
      context: ./backend/api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
      - user-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8085:8085"
    networks:
      - fantacalcio-net

volumes:
  postgres_data:

networks:
  fantacalcio-net:
    driver: bridge
