server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: asta-service
          uri: lb://ASTA-SERVICE
          predicates:
            - Path=/asta/**
        - id: player-service
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/player/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
